// <auto-generated />
using System;
using Infrastructure.Persistence.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251223173147_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("OrganizationMail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasFilter("[UserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3c44eb86-3d41-4229-9696-6caa57fb504e",
                            Email = "mehrdara1@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Mehr",
                            LastName = "Dara",
                            LockoutEnabled = false,
                            NormalizedEmail = "MEHRDARA1@GMAIL.COM",
                            NormalizedUserName = "MEHRDARA1",
                            OrganizationMail = "mehrdara1@gmail.com",
                            PasswordHash = "AQAAAAIAAYagAAAAEIXjHQxfUO9jTjQa5LMDIPFYRnb0DAsiH2uaQdZFb8MBIG00z3t7Hm2X0mxjcClB1g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6b89e8eb-e0da-4c58-82c5-b88b65cbcde6",
                            TwoFactorEnabled = false,
                            UserName = "mehrdara1"
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7282908d-eb50-426f-b86f-483a95a2dcb4",
                            Email = "mehrdara2@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Mehr",
                            LastName = "Dara",
                            LockoutEnabled = false,
                            NormalizedEmail = "MEHRDARA2@GMAIL.COM",
                            NormalizedUserName = "MEHRDARA2",
                            OrganizationMail = "mehrdara2@gmail.com",
                            PasswordHash = "AQAAAAIAAYagAAAAEKwZbQ41oxC48yb0us5WDAjgx7gjh5FiblK3ASYf+Xhh6CZ5Dfc2pH5rKgiykzAWrw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c1250ea2-9bdf-4102-883e-b6eaf2e2f161",
                            TwoFactorEnabled = false,
                            UserName = "mehrdara2"
                        },
                        new
                        {
                            Id = 3,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f0a3a91b-b607-42e3-aadf-1fb4c2adac63",
                            Email = "mehrdara3@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Mehr",
                            LastName = "Dara",
                            LockoutEnabled = false,
                            NormalizedEmail = "MEHRDARA3@GMAIL.COM",
                            NormalizedUserName = "MEHRDARA3",
                            OrganizationMail = "mehrdara3@gmail.com",
                            PasswordHash = "AQAAAAIAAYagAAAAEPYaX5pdGR7+Q4CR1jv6vuQAV/sR2GWCiKbaVMlidAwE6cemSFoAMTdCXhWDS8b72Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "bb47fb7b-8ec0-42e8-99fc-17349c267954",
                            TwoFactorEnabled = false,
                            UserName = "mehrdara3"
                        },
                        new
                        {
                            Id = 4,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4687a540-db49-45d0-985f-83f34afedfda",
                            Email = "mehrdara4@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Mehr",
                            LastName = "Dara",
                            LockoutEnabled = false,
                            NormalizedEmail = "MEHRDARA4@GMAIL.COM",
                            NormalizedUserName = "MEHRDARA4",
                            OrganizationMail = "mehrdara4@gmail.com",
                            PasswordHash = "AQAAAAIAAYagAAAAEEFZnh9AvjCN0kClnoVD4Hmk8YdRRFikfNHLrIIE1R/3TLseGI/USO5aN902/P2FMg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "74075db2-fd62-4908-85b8-c90d1d5032df",
                            TwoFactorEnabled = false,
                            UserName = "mehrdara4"
                        },
                        new
                        {
                            Id = 5,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d75a1866-f636-4409-a83f-f33121db0c6c",
                            Email = "mehrdara5@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Mehr",
                            LastName = "Dara",
                            LockoutEnabled = false,
                            NormalizedEmail = "MEHRDARA5@GMAIL.COM",
                            NormalizedUserName = "MEHRDARA5",
                            OrganizationMail = "mehrdara5@gmail.com",
                            PasswordHash = "AQAAAAIAAYagAAAAEOuutCneRmRdFkNHQxwn/jejqbwvHe/sZW7LrnKuPlEhI+tMPPbV8Xaq5wp87aBKjA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8a0566c4-cf4e-4c2a-bdfd-b8cb7b41c87b",
                            TwoFactorEnabled = false,
                            UserName = "mehrdara5"
                        },
                        new
                        {
                            Id = 6,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fd855e00-ef0a-4dac-a03b-2fee653324a1",
                            Email = "mehrdara6@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Mehr",
                            LastName = "Dara",
                            LockoutEnabled = false,
                            NormalizedEmail = "MEHRDARA6@GMAIL.COM",
                            NormalizedUserName = "MEHRDARA6",
                            OrganizationMail = "mehrdara6@gmail.com",
                            PasswordHash = "AQAAAAIAAYagAAAAEHAIoIE14iDluZpY1i7ev4pZbeclTSq+03m1Z6d6L+QHy6Url/+2Li8LLY0s/6h2dg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "7e23a298-31a1-4d43-93d0-2d777993fbfc",
                            TwoFactorEnabled = false,
                            UserName = "mehrdara6"
                        },
                        new
                        {
                            Id = 7,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e60dcda6-19cf-4031-bca8-660a1a1918bd",
                            Email = "mehrdara7@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Mehr",
                            LastName = "Dara",
                            LockoutEnabled = false,
                            NormalizedEmail = "MEHRDARA7@GMAIL.COM",
                            NormalizedUserName = "MEHRDARA7",
                            OrganizationMail = "mehrdara7@gmail.com",
                            PasswordHash = "AQAAAAIAAYagAAAAEJuVQHb5nn63kFfcYUMs7wB8yTBEjMpAPktHZwhTkV4Pnlf0hKwImEHq7pzC2oGq7w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "4c74704f-f9b0-4de5-aa06-03076b60e6dd",
                            TwoFactorEnabled = false,
                            UserName = "mehrdara7"
                        },
                        new
                        {
                            Id = 8,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "49ec161e-4c9d-48fe-bdf0-3a3d8cf96928",
                            Email = "mehrdara8@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Mehr",
                            LastName = "Dara",
                            LockoutEnabled = false,
                            NormalizedEmail = "MEHRDARA8@GMAIL.COM",
                            NormalizedUserName = "MEHRDARA8",
                            OrganizationMail = "mehrdara8@gmail.com",
                            PasswordHash = "AQAAAAIAAYagAAAAEC1kdYcv0o/tG4Ok1fpG8Cy6dtnc9KPwjNq6sOurnep6OBDbGi8kVBU+61yD1NdmgQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "9dd64414-d786-4d48-87be-8bb3a7b8c57c",
                            TwoFactorEnabled = false,
                            UserName = "mehrdara8"
                        },
                        new
                        {
                            Id = 9,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0a2920e9-547e-477e-8478-c329047c950c",
                            Email = "mehrdara9@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Mehr",
                            LastName = "Dara",
                            LockoutEnabled = false,
                            NormalizedEmail = "MEHRDARA9@GMAIL.COM",
                            NormalizedUserName = "MEHRDARA9",
                            OrganizationMail = "mehrdara9@gmail.com",
                            PasswordHash = "AQAAAAIAAYagAAAAEEXyr0lsKfoW3INlBuCarDIWW2c1DDxKhkRlnsptSkZ18eQjtVFZAnRIwmgVBkYXFA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "bca3901a-5cb6-44df-ada3-540d3fb5b6e5",
                            TwoFactorEnabled = false,
                            UserName = "mehrdara9"
                        },
                        new
                        {
                            Id = 10,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2b705fe8-4881-4c67-86f2-83865cd5d2cc",
                            Email = "mehrdara10@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Mehr",
                            LastName = "Dara",
                            LockoutEnabled = false,
                            NormalizedEmail = "MEHRDARA10@GMAIL.COM",
                            NormalizedUserName = "MEHRDARA10",
                            OrganizationMail = "mehrdara10@gmail.com",
                            PasswordHash = "AQAAAAIAAYagAAAAEOijlVTmWe/90gokssArWMZ1qPuYEvlJJxxIlL27z6jdA+tJjzPnYRS8LBINEXR3pQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "90788236-7ad9-40f2-aeda-a9446fad8ded",
                            TwoFactorEnabled = false,
                            UserName = "mehrdara10"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Letter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedUserId")
                        .HasColumnType("int");

                    b.Property<string>("File")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("LetterNumber")
                        .HasColumnType("bigint");

                    b.Property<byte>("LetterType")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedUserId")
                        .HasColumnType("int");

                    b.Property<int?>("ParentLetterId")
                        .HasColumnType("int");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ParentLetterId");

                    b.HasIndex("SenderId");

                    b.ToTable("Letters", t =>
                        {
                            t.HasCheckConstraint("CK_Letter_Body_NotEmpty", "LEN(TRIM(Body)) > 0");

                            t.HasCheckConstraint("CK_Letter_Subject_NotEmpty", "LEN(TRIM(Subject)) > 0");

                            t.HasCheckConstraint("CK_Letter_Type", "[LetterType] IN (1, 2, 3)");
                        });
                });

            modelBuilder.Entity("Domain.Entities.LetterRecipient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedUserId")
                        .HasColumnType("int");

                    b.Property<int?>("ForwardedByUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<int>("LetterId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RecipientId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ForwardedByUserId");

                    b.HasIndex("RecipientId");

                    b.HasIndex("LetterId", "RecipientId")
                        .IsUnique();

                    b.ToTable("LetterRecipient", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Letter", b =>
                {
                    b.HasOne("Domain.Entities.Letter", "ParentLetter")
                        .WithMany("Replies")
                        .HasForeignKey("ParentLetterId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Domain.Entities.AppUser", "Sender")
                        .WithMany("SentLetters")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ParentLetter");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Domain.Entities.LetterRecipient", b =>
                {
                    b.HasOne("Domain.Entities.AppUser", "ForwarderUser")
                        .WithMany()
                        .HasForeignKey("ForwardedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entities.Letter", "Letter")
                        .WithMany("Recipients")
                        .HasForeignKey("LetterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.AppUser", "Recipient")
                        .WithMany("ReceivedLetters")
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ForwarderUser");

                    b.Navigation("Letter");

                    b.Navigation("Recipient");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.AppUser", b =>
                {
                    b.Navigation("ReceivedLetters");

                    b.Navigation("SentLetters");
                });

            modelBuilder.Entity("Domain.Entities.Letter", b =>
                {
                    b.Navigation("Recipients");

                    b.Navigation("Replies");
                });
#pragma warning restore 612, 618
        }
    }
}
