// <auto-generated />
using System;
using Infrastructure.Persistence.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("OrganizationMail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasFilter("[UserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c18ec524-0aeb-4bd9-8c3c-c7c9cc1506f3",
                            Email = "mehrdara1@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Mehr",
                            LastName = "Dara",
                            LockoutEnabled = false,
                            NormalizedEmail = "MEHRDARA1@GMAIL.COM",
                            NormalizedUserName = "MEHRDARA1",
                            OrganizationMail = "mehrdara1@gmail.com",
                            PasswordHash = "AQAAAAIAAYagAAAAEG/MT7Ol4Ep0B4KtE1YUoX98nZZ10UatuyX54DTDNih603h/qRmXBZcQIZqh67YsDw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "dba3efa3-f1be-404e-95f6-2b5441f1691a",
                            TwoFactorEnabled = false,
                            UserName = "mehrdara1"
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "cea1cace-bc23-428b-a1ae-4b2b951d9053",
                            Email = "mehrdara2@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Mehr",
                            LastName = "Dara",
                            LockoutEnabled = false,
                            NormalizedEmail = "MEHRDARA2@GMAIL.COM",
                            NormalizedUserName = "MEHRDARA2",
                            OrganizationMail = "mehrdara2@gmail.com",
                            PasswordHash = "AQAAAAIAAYagAAAAEMw+Sf3g20xAFEyjp/QWjw1CT/Waejc1khTfDwppTC600TPUc64Qhfor28Gmxt56sA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6eee75d4-704b-4c78-b444-950a430c3686",
                            TwoFactorEnabled = false,
                            UserName = "mehrdara2"
                        },
                        new
                        {
                            Id = 3,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "deace663-2957-4629-a78f-f036980c3883",
                            Email = "mehrdara3@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Mehr",
                            LastName = "Dara",
                            LockoutEnabled = false,
                            NormalizedEmail = "MEHRDARA3@GMAIL.COM",
                            NormalizedUserName = "MEHRDARA3",
                            OrganizationMail = "mehrdara3@gmail.com",
                            PasswordHash = "AQAAAAIAAYagAAAAECPut6KDt1uu7DgZAQjddJBEj28MCkF1tgRcMAG20c+24RJihnjHNsz73sMQPAji2g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "196dde20-feba-47cf-8b7e-adba07af6c8f",
                            TwoFactorEnabled = false,
                            UserName = "mehrdara3"
                        },
                        new
                        {
                            Id = 4,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e164c672-7ff8-45fe-98f4-93d02f5713b2",
                            Email = "mehrdara4@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Mehr",
                            LastName = "Dara",
                            LockoutEnabled = false,
                            NormalizedEmail = "MEHRDARA4@GMAIL.COM",
                            NormalizedUserName = "MEHRDARA4",
                            OrganizationMail = "mehrdara4@gmail.com",
                            PasswordHash = "AQAAAAIAAYagAAAAEMPeQ05svicEzvg5a5TbpWuTXrHgzJ1kYnHZHyOQoLF3hxqVB4PBmrje0KZEbdTAYg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c2f4e9c1-47da-4fae-b54f-9938f2872949",
                            TwoFactorEnabled = false,
                            UserName = "mehrdara4"
                        },
                        new
                        {
                            Id = 5,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "eba1690e-13f6-40ba-83b0-69f02c3e9602",
                            Email = "mehrdara5@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Mehr",
                            LastName = "Dara",
                            LockoutEnabled = false,
                            NormalizedEmail = "MEHRDARA5@GMAIL.COM",
                            NormalizedUserName = "MEHRDARA5",
                            OrganizationMail = "mehrdara5@gmail.com",
                            PasswordHash = "AQAAAAIAAYagAAAAEAlKFJOOeygYCNMCfGwvlPrPSWElZFghpeB11b0D+1x/cqXwJe2R0hTJKbuLR9Ztvg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "7000498c-d458-49fe-9b7a-d2d38da501ef",
                            TwoFactorEnabled = false,
                            UserName = "mehrdara5"
                        },
                        new
                        {
                            Id = 6,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "413b155d-4f86-430e-b58d-cafb23877674",
                            Email = "mehrdara6@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Mehr",
                            LastName = "Dara",
                            LockoutEnabled = false,
                            NormalizedEmail = "MEHRDARA6@GMAIL.COM",
                            NormalizedUserName = "MEHRDARA6",
                            OrganizationMail = "mehrdara6@gmail.com",
                            PasswordHash = "AQAAAAIAAYagAAAAEIgTAL8KEWCMfs2p1gJ6C6owq2w7VpnEKubFnVtmk1INmK0u9aEb6t2jiRucB0EjKQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d32c8b67-95c5-4623-a5b8-9f2ddc3dea77",
                            TwoFactorEnabled = false,
                            UserName = "mehrdara6"
                        },
                        new
                        {
                            Id = 7,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a1f6f989-ce4d-4489-af9c-08d2731eb30f",
                            Email = "mehrdara7@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Mehr",
                            LastName = "Dara",
                            LockoutEnabled = false,
                            NormalizedEmail = "MEHRDARA7@GMAIL.COM",
                            NormalizedUserName = "MEHRDARA7",
                            OrganizationMail = "mehrdara7@gmail.com",
                            PasswordHash = "AQAAAAIAAYagAAAAELqSV4mumBlPbNMlgTdTJSfyEPlx17sPeS0Tza8n4As2lvGZ/BiLmXA0ZEd1GLrhYQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ea04585b-16d9-4023-84bb-3b7042db104c",
                            TwoFactorEnabled = false,
                            UserName = "mehrdara7"
                        },
                        new
                        {
                            Id = 8,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2f74c066-b934-4b57-a919-fc86c1eee8e8",
                            Email = "mehrdara8@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Mehr",
                            LastName = "Dara",
                            LockoutEnabled = false,
                            NormalizedEmail = "MEHRDARA8@GMAIL.COM",
                            NormalizedUserName = "MEHRDARA8",
                            OrganizationMail = "mehrdara8@gmail.com",
                            PasswordHash = "AQAAAAIAAYagAAAAEG7LVLY0ZycuoRAaygeXUGa3EbIXEK4vhRdRQPPaWtNAmkJZG23swWif9oCR0Z04xQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "194a73a2-6ae9-416a-b7b8-6802cc199e54",
                            TwoFactorEnabled = false,
                            UserName = "mehrdara8"
                        },
                        new
                        {
                            Id = 9,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3704569b-f5b8-462f-bf7e-91f07992621c",
                            Email = "mehrdara9@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Mehr",
                            LastName = "Dara",
                            LockoutEnabled = false,
                            NormalizedEmail = "MEHRDARA9@GMAIL.COM",
                            NormalizedUserName = "MEHRDARA9",
                            OrganizationMail = "mehrdara9@gmail.com",
                            PasswordHash = "AQAAAAIAAYagAAAAEEToSG7InvPeAB7WZN4l0G7iQPVWhupq/Z+V3T7ftTbITFFp+oV4brnvCRNRJlT4Bg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e911c85c-8d75-41cd-91dd-d5dc14811075",
                            TwoFactorEnabled = false,
                            UserName = "mehrdara9"
                        },
                        new
                        {
                            Id = 10,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "942b31c8-8562-4d5e-a037-a2e50ab86a9c",
                            Email = "mehrdara10@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Mehr",
                            LastName = "Dara",
                            LockoutEnabled = false,
                            NormalizedEmail = "MEHRDARA10@GMAIL.COM",
                            NormalizedUserName = "MEHRDARA10",
                            OrganizationMail = "mehrdara10@gmail.com",
                            PasswordHash = "AQAAAAIAAYagAAAAEOua3ryNw+3/owv9JBlOx/5ZB2apMtz0UFNE0RccjeixthazVsAcF3g/PWI6sbeN8g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d6192833-4ace-4dfc-b799-59bffd04bec7",
                            TwoFactorEnabled = false,
                            UserName = "mehrdara10"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Letter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedUserId")
                        .HasColumnType("int");

                    b.Property<string>("File")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("LetterNumber")
                        .HasColumnType("bigint");

                    b.Property<byte>("LetterType")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedUserId")
                        .HasColumnType("int");

                    b.Property<int?>("ParentLetterId")
                        .HasColumnType("int");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ParentLetterId");

                    b.HasIndex("SenderId");

                    b.ToTable("Letters", t =>
                        {
                            t.HasCheckConstraint("CK_Letter_Body_NotEmpty", "LEN(TRIM(Body)) > 0");

                            t.HasCheckConstraint("CK_Letter_Subject_NotEmpty", "LEN(TRIM(Subject)) > 0");

                            t.HasCheckConstraint("CK_Letter_Type", "[LetterType] IN (1, 2, 3)");
                        });
                });

            modelBuilder.Entity("Domain.Entities.LetterRecipient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedUserId")
                        .HasColumnType("int");

                    b.Property<int?>("ForwardedByUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<int>("LetterId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RecipientId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ForwardedByUserId");

                    b.HasIndex("RecipientId");

                    b.HasIndex("LetterId", "RecipientId")
                        .IsUnique();

                    b.ToTable("LetterRecipient", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Letter", b =>
                {
                    b.HasOne("Domain.Entities.Letter", "ParentLetter")
                        .WithMany("Replies")
                        .HasForeignKey("ParentLetterId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Domain.Entities.AppUser", "Sender")
                        .WithMany("SentLetters")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ParentLetter");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Domain.Entities.LetterRecipient", b =>
                {
                    b.HasOne("Domain.Entities.AppUser", "ForwarderUser")
                        .WithMany()
                        .HasForeignKey("ForwardedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entities.Letter", "Letter")
                        .WithMany("Recipients")
                        .HasForeignKey("LetterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.AppUser", "Recipient")
                        .WithMany("ReceivedLetters")
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ForwarderUser");

                    b.Navigation("Letter");

                    b.Navigation("Recipient");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.AppUser", b =>
                {
                    b.Navigation("ReceivedLetters");

                    b.Navigation("SentLetters");
                });

            modelBuilder.Entity("Domain.Entities.Letter", b =>
                {
                    b.Navigation("Recipients");

                    b.Navigation("Replies");
                });
#pragma warning restore 612, 618
        }
    }
}
